---
- name: Check if /etc/debian_version exists
  ansible.builtin.stat:
    path: /etc/debian_version
  register: stat_etc_debian_version

# On Ubuntu the default shell is dash
# dash doesn't support pipefail.
#
# Ensure that bash is installed, and use bash as the shell executable

- name: Ensure bash is installed
  ansible.builtin.package:
    name: bash
    state: present

- name: Map debian version to debian_codename
  when:
    - stat_etc_debian_version.stat.exists
  block:
    - name: Get the debian code name
      ansible.builtin.shell: |
        set -o errexit
        set -o pipefail
        set -o nounset

        cat /etc/debian_version | head -1 | cut -f 1 -d '/'
      args:
        executable:
          bash
      register: shell_get_debian_codename
      changed_when: false
    - name: Display shell_get_debian_codename
      ansible.builtin.debug:
        msg:
          - "{{ shell_get_debian_codename }}"
      tags:
        - never
        - debug
    - name: Set debian_codename
      ansible.builtin.set_fact:
        debian_codename: "{{ shell_get_debian_codename.stdout_lines[0] }}"
    - name: Display debian_codename
      ansible.builtin.debug:
        msg:
          - "{{ debian_codename }}"
      tags:
        - never
        - debug

- name: Install the required Debian packages
  ansible.builtin.include_tasks: "{{ install_debian }}"
  with_first_found:
    - Debian_os_family/{{ debian_codename }}.yml
    - Debian_os_family/defaults.yml
  loop_control:
    loop_var: install_debian
