---
- name: Install the libvirt packages
  become: true
  ansible.builtin.package:
    name:
      - qemu-system
      - libvirt-clients
      - libvirt-daemon-system
      - bridge-utils
  notify:
    - Reload libvirtd
